import { Currency } from "@/lib/types"

export const CURRENCIES: Record<string, Currency> = {
  EUR: { code: 'EUR', symbol: '€', name: 'Euro' },
  AUD: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  BRL: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  CAD: { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  CHF: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  CNY: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  CZK: { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  DKK: { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  GBP: { code: 'GBP', symbol: '£', name: 'British Pound Sterling' },
  HKD: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  HUF: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  IDR: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  ILS: { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
  INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  ISK: { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  KRW: { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  MXN: { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  MYR: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  NOK: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  NZD: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  PHP: { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  PLN: { code: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
  RON: { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  SEK: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  SGD: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  THB: { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  TRY: { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  USD: { code: 'USD', symbol: '$', name: 'United States Dollar' },
  ZAR: { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
}